### ISSUE TITLE
Firmware dead with the latest firmware

### ISSUE THREAD

**Issue by 1176321897** [boricj/ripem#3]
Hello,
  My calculator broke down when I'm trying to flash the three-party firmware.The hardware version of the calculator is C,with the firmware 2016 08 29(10637).
  The firmware format has been changed in this firmware version.I flashed the PRIME_APP.DAT to my udisk with 8192 bytes of offset.Then I found the file named armfir.elf,so I replaced the elf,changed the md5 ,copied my udisk into PRIME_APP.DAT and flashed the firmware into my calculator.But my calculator restarted in the start screen “x^2+y^2=1".When I tried copying the rom file generated by the program elf2rom,the calculator does not display anything unless you start it with CFO pressed or Symb button pressed.
  PS:the source code can't be compiled in Windows but in ubantu, but I don't know which library I should install in WIndows.
http://www.hpmuseum.org/forum/thread-8483.html

**Comment by boricj** [comment]
You need to flash the generated PRIME_OS.ROM file to install Rip'Em (https://github.com/boricj/ripem#how-to-install).

A quick look at the 10637 firmware suggests nothing has changed that would impact Rip'Em. I haven't tried it in a long time, but it should still work.

**Comment by 1176321897** [comment]
The command make returned an error:
```
arm-none-eabi-ar rcs lib/libhpbsp/libhpbsp.a
arm-none-eabi-ar rcs lib/libhputils/libhputils.a
arm-none-eabi-ar rcs lib/libtinf/libtinf.a
arm-none-eabi-gcc -nostdlib -ffreestanding -s -n -T bin/dummy/ldscript lib/libhpbsp/libhpbsp.a lib/libhputils/libhputils.a -lgcc -o bin/dummy/dummy.elf --entry 0x30000000
arm-none-eabi-gcc -nostdlib -ffreestanding -s -n -T bin/gdbstub/ldscript lib/libhpbsp/libhpbsp.a lib/libhputils/libhputils.a -lgcc -o bin/gdbstub/gdbstub_serial.elf --entry 0x00002000
arm-none-eabi-gcc -nostdlib -ffreestanding -s -n -T bin/dumbcalc/ldscript lib/libhpbsp/libhpbsp.a lib/libhputils/libhputils.a -lgcc -o bin/dumbcalc/dumbcalc.elf --entry 0x30000000
rm -rf bin/ripem/tmp
rm -f bin/ripem/payload
mkdir bin/ripem/tmp
cp -f bin/dummy/dummy.elf bin/gdbstub/gdbstub_serial.elf bin/dumbcalc/dumbcalc.elf bin/ripem/tmp
gzip -9 bin/ripem/tmp/*
cd bin/ripem/tmp && ls | cpio -ov -H newc > ../payload.cpio
dumbcalc.elf.gz
dummy.elf.gz
gdbstub_serial.elf.gz
2 blocks
arm-none-eabi-objcopy -I binary -O elf32-littlearm -B arm --rename-section .data=.payload bin/ripem/payload.cpio bin/ripem/ripem_payload.o
arm-none-eabi-gcc -nostdlib -ffreestanding -s -n -T bin/ripem/ldscript bin/ripem/ripem_payload.o lib/libhpbsp/libhpbsp.a lib/libhputils/libhputils.a lib/libtinf/libtinf.a -lgcc -o bin/ripem/ripem.elf --entry 0x31000020
cc -Wall -Itools/ -o tools/osrom2elf/osrom2elf tools/osrom2elf/osrom2elf.c  -lelf
tools/osrom2elf/osrom2elf.c: In function ‘load_elf’:
tools/osrom2elf/osrom2elf.c:107:2: warning: implicit declaration of function ‘elf_getdata_rawchunk’ [-Wimplicit-function-declaration]
  LIBELF_CHECK(inPath, elf_Data = elf_getdata_rawchunk(elf, elf_Phdr[0].p_offset, elf_Phdr[0].p_filesz, ELF_T_PHDR), err2);
  ^
In file included from tools/osrom2elf/osrom2elf.c:10:0:
tools/osrom2elf/osrom2elf.c:107:32: warning: assignment makes pointer from integer without a cast [enabled by default]
  LIBELF_CHECK(inPath, elf_Data = elf_getdata_rawchunk(elf, elf_Phdr[0].p_offset, elf_Phdr[0].p_filesz, ELF_T_PHDR), err2);
                                ^
tools/libelf_check_macros.h:23:8: note: in definition of macro ‘LIBELF_CHECK’
  if (!(a)) { \
        ^
ln -sf osrom2elf tools/osrom2elf/elf2osrom
tools/osrom2elf/elf2osrom bin/ripem/ripem.elf bin/ripem/PRIME_OS.ROM
```
Can you tell me why?

**Comment by boricj** [comment]
The `make` command did not fail, although there are indeed a couple of warnings from the `osrom2elf` tool.

The `PRIME_OS.ROM` binary has been generated under `bin/ripem`. This is the file that you want to flash onto your calculator.

**Comment by 1176321897** [comment]
I have flashed my calculator as you told and it can only enter the recovery mode.And for some reason I can‘t flash my calculator back.
http://www.hpmuseum.org/forum/thread-8508.html

**Comment by boricj** [comment]
Closed as real issue was outdated GNU Make (http://www.hpmuseum.org/forum/thread-8508-post-74932.html#pid74932) under Ubuntu 14.04.

Building Rip'Em currently requires GNU Make >= 4.0, otherwise the generated firmware will be an empty shell due to malfunctioning Makefile macros.
